<img src = 'https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true' width="240" height="360">
# __Assignment: Numpy and Pandas__
### Level: 1

### 1. Create a null vector of size 7 but the third and last value as 2.

In [1]:
import numpy as np
def generate():
    nv = np.zeros(7)
    nv[6]=2
    nv[2]=2
    return nv # your variable 
generate()

array([0., 0., 2., 0., 0., 0., 2.])

### 2. Create a vector of size 9 with values ranging from 0 to 2, both excluded.

In [37]:
import numpy as np
def generate():
    vec = np.linspace(0,2,11)
    print(vec)
    return vec[1:10] # your variable
generate() 

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

### 3. Convert the first character of each element in a series to uppercase? And return the new series.

In [2]:
import pandas as pd
series = pd.Series(['how', 'to', 'learn', 'data science?'])
def generate():
    v= series.str.upper()
    return v # your variable for new series
generate() 

0              HOW
1               TO
2            LEARN
3    DATA SCIENCE?
dtype: object

### 4. Given a 3*3 matrix named matrix_fab, From each element of this matrix subtract the mean of that row, name this matrix as matrix_sub. Divide each element of this matrix by twice of the largest element to get matrix_norm. Print it out.

In [3]:
import numpy as np
arr = np.arange(0,9)                                
matrix_fab = arr.reshape(3,3)
def generate():
    print('matrix_fab\n',matrix_fab)
    #matrix_fab.mean(axis = 1, keepdims = True)
    matrix_mean = np.mean(matrix_fab,axis=1,keepdims=True)   
    matrix_sub =matrix_fab - matrix_mean
    max= matrix_sub.max() *2
    matrix_norm= matrix_sub/max
    
    print('matrix_mean',matrix_mean)
    print('matrix_sub',matrix_sub)
    print('matrix_norm',matrix_norm)
    
    return None
generate()

matrix_fab
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
matrix_mean [[1.]
 [4.]
 [7.]]
matrix_sub [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
matrix_norm [[-0.5  0.   0.5]
 [-0.5  0.   0.5]
 [-0.5  0.   0.5]]


### 5. Create a random vector of size 12 , sort it in decreasing order, make 4*3 array using it.
Hint: use reshape and sort function.

In [16]:
import numpy as np
x = np.random.random(12)
print(x)
x.sort()
print()
print(0)
y= x.reshape(4,3)
print(y)

[0.64373939 0.31557324 0.50320097 0.3061919  0.57783338 0.44696646
 0.99487794 0.56823512 0.8678379  0.53368055 0.31896166 0.16434513]

0
[[0.16434513 0.3061919  0.31557324]
 [0.31896166 0.44696646 0.50320097]
 [0.53368055 0.56823512 0.57783338]
 [0.64373939 0.8678379  0.99487794]]


In [22]:
import numpy as np
def generate():
    arr1= np.random.random(12)
    print('arr1\n',arr1)
    arr2=np.sort(arr1,axis=0)
    print('arr1 sorted \n',arr2)
    arr2 = arr2.reshape(4,3)
    return arr2 #your variable
generate()

arr1
 [0.8910946  0.34234026 0.42714686 0.42380839 0.78644624 0.65834994
 0.76795307 0.2673882  0.3452232  0.23834466 0.702609   0.2051149 ]
arr1 sorted 
 [0.2051149  0.23834466 0.2673882  0.34234026 0.3452232  0.42380839
 0.42714686 0.65834994 0.702609   0.76795307 0.78644624 0.8910946 ]


array([[0.2051149 , 0.23834466, 0.2673882 ],
       [0.34234026, 0.3452232 , 0.42380839],
       [0.42714686, 0.65834994, 0.702609  ],
       [0.76795307, 0.78644624, 0.8910946 ]])

### 6. Below is Python dictionary data and Python list labels. Create a DataFrame df from this dictionary data which has index as labels. Select the rows where the age is missing, i.e. is NaN.

In [74]:
import numpy as np
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
import pandas as pd
def generate():
    df=pd.DataFrame(data)         # create dataframe
    df['labels']=labels           # add column   
    df1 = df.set_index('labels')  # set the newly added column as index
    print('df1\n',df1)
    
    df2= df1.dropna()                      # to drop rows with nulls/NaN
    print('\ndf2 with only nulls \n',df2)
    
    df3=df1[pd.isnull(df1['age'])]          # to retain rows with nulls/NaN
    print('\ndf3 with only nulls \n',df3)
    return None                          # your variable
generate()

df1
        animal  age  visits priority
labels                             
a         cat  2.5       1      yes
b         cat  3.0       3      yes
c       snake  0.5       2       no
d         dog  NaN       3      yes
e         dog  5.0       2       no
f         cat  2.0       3       no
g       snake  4.5       1       no
h         cat  NaN       1      yes
i         dog  7.0       2       no
j         dog  3.0       1       no

df2 with only nulls 
        animal  age  visits priority
labels                             
a         cat  2.5       1      yes
b         cat  3.0       3      yes
c       snake  0.5       2       no
e         dog  5.0       2       no
f         cat  2.0       3       no
g       snake  4.5       1       no
i         dog  7.0       2       no
j         dog  3.0       1       no

df3 with only nulls 
        animal  age  visits priority
labels                             
d         dog  NaN       3      yes
h         cat  NaN       1      yes


### 7. From the give dataframe df, in the 'animal' column change the 'dog' entries to 'Labrador', change the age in row 'd' to 2.7 and calculate the mean age (name it mean_age) for each different animal in df. Print df and return mean_age.

In [139]:
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df =pd.DataFrame(data) 
df['labels']=labels
#print(df)
df.set_index('labels',inplace=True)
print('df\n',df)
    
df1 = df.replace('dog','Labrador')                                               # using replace function on whole df
print('df1\n',df1)

df['animal'] = df.replace('dog','Labrador')                                      # using replace function on whole df
print('df--\n',df)

df['animal1']= df['animal'].map(lambda x: x.replace('dog','Labrador'))           # using apply & lambda function
df

df['animal2']=df['animal'].apply(lambda x: x.replace('dog','Labrador'))          # using map & lambda function
df

## replacing age by 2.7 where index is 'd'
df.loc['d','age']=2.7
mean_age = df.groupby('animal')['age'].mean()
print('final df\n',mean_age)

df.groupby('animal')['visits'].mean()

df
        animal  age  visits priority
labels                             
a         cat  2.5       1      yes
b         cat  3.0       3      yes
c       snake  0.5       2       no
d         dog  NaN       3      yes
e         dog  5.0       2       no
f         cat  2.0       3       no
g       snake  4.5       1       no
h         cat  NaN       1      yes
i         dog  7.0       2       no
j         dog  3.0       1       no
df1
           animal  age  visits priority
labels                                
a            cat  2.5       1      yes
b            cat  3.0       3      yes
c          snake  0.5       2       no
d       Labrador  NaN       3      yes
e       Labrador  5.0       2       no
f            cat  2.0       3       no
g          snake  4.5       1       no
h            cat  NaN       1      yes
i       Labrador  7.0       2       no
j       Labrador  3.0       1       no
df--
           animal  age  visits priority
labels                                
a      

animal
Labrador    2.0
cat         2.0
snake       1.5
Name: visits, dtype: float64

### 8.  From the given dataframe get the positions where values of two columns match?

In [150]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})
print(df,'\n')
def generate():
    x= np.where(df.fruit1==df.fruit2)  # your code here
    print(x)
    return None
generate()

   fruit1  fruit2
0  banana  orange
1  orange  banana
2   apple  banana
3  banana   apple
4  banana  orange
5  orange   apple
6  orange   apple
7  orange  banana
8  orange  orange
9   apple   apple 

(array([8, 9], dtype=int64),)


### 9. Find the positions of numbers that are multiples of 4 from a series? Print series and return position. Hint: use argwhere.

In [39]:
import pandas as pd
import numpy as np
series = pd.Series(np.random.randint(1, 10, 7))
print(series)
def generate():
    position= np.argwhere(series % 2==0)
    print(type(position),position)
    return # your variable
generate()

0    8
1    5
2    6
3    3
4    8
5    7
6    2
dtype: int32
<class 'numpy.ndarray'> [[0]
 [2]
 [4]
 [6]]


### 10. Stack two given series vertically and horizontally ? Print out both.

In [51]:
import pandas as pd
import numpy as np
series1 = pd.Series(range(5))
series2 = pd.Series(list('abcde'))
print(series1, series2)
def generate():
    horh =np.append(series1,series2)
    print(horh)
    
    vert = pd.concat([series1,series2],axis=1)
    print(vert)
    # print out both vertically and horizontally stacked series.
    return None
generate()

0    0
1    1
2    2
3    3
4    4
dtype: int64 0    a
1    b
2    c
3    d
4    e
dtype: object
[0 1 2 3 4 'a' 'b' 'c' 'd' 'e']
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
