In [2]:
import numpy as np
import time

In [20]:
time.time()

def numpy_version():
    myarr1= np.arange(1000000)
    sumarr1=myarr1+2
    print(sumarr1)

numpy_version()

[      2       3       4 ...  999999 1000000 1000001]


In [3]:
list1=[[1,2,3,4],[5,6,7,8]]
print(list1)
a2=np.array(list1)
print("a2 :",a2)

#a1[::2]

[[1, 2, 3, 4], [5, 6, 7, 8]]
a2 : [[1 2 3 4]
 [5 6 7 8]]


In [4]:
import time
import numpy as np

size_of_vec = 1000000

def pure_python_version():                                                # This function will return the time for python calculation
    time_python = time.time()                                             # Start time before operation
    my_list1 = range(size_of_vec)                                         # Creating a list with 1000000 values
    my_list2 = range(size_of_vec)
    sum_list = [my_list1[i] + my_list2[i] for i in range(len(my_list1))]  # Calculating the sum
    return time.time() - time_python                                      # Return Current time - start time

def numpy_version():                                                      # This function will return the time for numpy calculation
    time_numpy = time.time()                                              # Start time before operation
    my_arr1 = np.arange(size_of_vec)                                      # Creating a numpy array of 1000000 values
    my_arr2 = np.arange(size_of_vec)
    sum_array = my_arr1 + my_arr2                                         # Calculate the sum
    return time.time() - time_numpy  

python_time=pure_python_version()
numpy_time=numpy_version()
print("python time ",python_time)
print("Numpy time ",numpy_time)
print("Numpy in this example is {:0.4f} times faster than python computing".format(python_time/numpy_time))

python time  1.6200926303863525
Numpy time  0.005000114440917969
Numpy in this example is 324.0111 times faster than python computing


  ### key feature of numpy is N dimensional array or ndarray

In [2]:
import numpy as np
list2 = [[2,3,'f'],[3,5,6]]
print("list :",list2)
arr_2d=np.array(list2)
print(arr_2d)
print(type(arr_2d))


list : [[2, 3, 'f'], [3, 5, 6]]
[['2' '3' 'f']
 ['3' '5' '6']]
<class 'numpy.ndarray'>


### shape gives the array shape or matrix type such as MxN  
### dim gives the dimensions of array

In [12]:
print(arr_2d)

print("Shape of array :",np.shape(arr_2d))

print("Dim of array:",np.ndim(arr_2d))

[['2' '3' 'f']
 ['3' '5' '6']]
Shape of array : (2, 3)
Dim of array: 2


In [17]:
list3 = [10,24,42,90,45]
print("list3 :{} and its type {}:".format(list3,type(list3)))

arr_1d =np.array(list3)
print("{} is {} dimensional array".format(arr_1d, np.ndim(arr_1d)))

print("dim of the array1 :",np.ndim(arr_1d))
print("shape of array1 :",np.shape(arr_1d))

list3 :[10, 24, 42, 90, 45] and its type <class 'list'>:
[10 24 42 90 45] is 1 dimensional array
dim of the array1 : 1
shape of array1 : (5,)


__ndarrays are widely used for handling images. It is easier to use numpy arrays for image operations as compared to python lists.__

In [20]:
print([1,2])           # 1d array
print([[1,2],[1,2]])   # 2d array

[1, 2]
[[1, 2], [1, 2]]


In [28]:
mat1=[[1,2,3],[4,5,6],[7,8,9],[11,22,33]]
arr3 = np.array(mat1)
print("This is type(arr3)",mat1)
print(type(mat1))
print()
print(arr3)
print(type(arr3))

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 22, 33]]
<class 'list'>

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]]
<class 'numpy.ndarray'>


In [30]:
arr_1d.shape

(5,)

In [33]:
arr_2d.ndim
arr_2d.shape

(2, 3)

###  np.ndim( array-name-argument)   -- function 
### array-name.ndim    -- method

### np.shape(array-name-argument)  -- function
### array-name.shape   -- method

In [39]:
print(arr3.shape)

print("{} is {} dimensional array".format(arr_1d, arr_1d.ndim))
print()
print("{} is {} dimensional array".format(arr_2d, np.ndim(arr_2d)))

(4, 3)
[10 24 42 90 45] is 1 dimensional array

[['2' '3' 'f']
 ['3' '5' '6']] is 2 dimensional array


__To know more about the layout of the array, for example for information regarding type, size and byte order of the data, dtype function is used__

In [43]:
arr3.dtype

dtype('int32')

### extracting different elements from array and list

In [3]:
import numpy as np

mat1=[[1,2,3],[4,5,6],[7,8,9],[11,22,33]]
print(mat1)
print()
arr3 = np.array(mat1)
print(arr3)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 22, 33]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 22 33]]


### to extract values user syntax as 
### array [row index,column index]


In [22]:
# to get the elements from second column.
arr3[::,1]        ## :: -> for printing all rows and 1-> for all data from second column

array([ 2,  5,  8, 22])

In [31]:
# to get the particular elements
arr3[::,:2]                 # :2 means range exclusive of 2

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [11, 22]])

### Array Initialization

In [33]:
ap=np.arange(1,10)            # this function acts like a range with higher limit exclusive
print(ap)

[1 2 3 4 5 6 7 8 9]


In [34]:
ap+2    # adding a number to matrix or array

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
ap*2    # multiplying by a number

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
ap -2   # subtracting a number

array([-1,  0,  1,  2,  3,  4,  5,  6,  7])

In [38]:
ap /2   # dividing by a number

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [40]:
ap % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

### if the array that you are creating doesnt have same number of rows from first list and columns from second list then it just creates an array of lists instead of matrix, like below.
1x2 and 1x3 --> this gives the array of lists.

In [50]:
list1 = [[1,2],[3,4,5]]
print(list1)

[[1, 2], [3, 4, 5]]


In [51]:
diff_arr= np.array(list1)
print(diff_arr)

[list([1, 2]) list([3, 4, 5])]


In [53]:
list2 = [[1,2,7],[3,4,5]]
print(np.array(list2))

[[1 2 7]
 [3 4 5]]


In [59]:
list1 = [[1,2],[3,4,5],[7,6,4]]
mat3 = np.array(list1) 
print(mat3)
print(np.ndim(mat3))
print(np.shape(mat3))

[list([1, 2]) list([3, 4, 5]) list([7, 6, 4])]
1
(3,)


### arange (start, stop, step)

In [61]:
np.arange(1,20,3)      # create array with step size of 3

array([ 1,  4,  7, 10, 13, 16, 19])

In [64]:
np.zeros(5)            # create array with the 5 zeros

array([0., 0., 0., 0., 0.])

In [77]:
print(np.zeros((2,3)))       # create a matrix of 0 of 2x3 shape.
print()
print(np.zeros((2,3)).ndim)

[[0. 0. 0.]
 [0. 0. 0.]]

2


In [97]:
print(mat1)
print(type(mat1))
print("dim of list :",np.ndim(mat1))

arr4 = np.array(mat1)
print(type(arr4))
print("dim of Array :",arr4.ndim)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 22, 33]]
<class 'list'>
dim of list : 2
<class 'numpy.ndarray'>
dim of Array : 2


In [127]:
arr_1=np.ones((6,4))                # identity matrix
print("Array1 \n",arr_1,'\n')

arr_2 = np.eye(4)                   # matrix with diagonal ones
print("Array2:\n",arr_2)

Array1 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Array2:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
import numpy as np
arr1 = np.zeros([3,2,4])  # this will create 
arr2 = np.ones([2,5])    # Identity matrix     
print(arr1)
print()
print(arr2)           # 

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]



In [30]:
arr2 = np.ones([2,5])    # Identity matrix     
print(arr2) 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### numpy creates everything as floats.  We can typecast it as int using .astype(int)

In [31]:
arr4 = np.ones([2,3]).astype(int)
print(arr4)

[[1 1 1]
 [1 1 1]]


### linspace  - used to create the equally spaced points. It created the items in the array by giving it same length.
<br>used to create equally spaced items on the line.

### linspace(start, end, no values to plot)

In [45]:
np.linspace(0,4,20)          # to calculate the elements on the axis ->  range/(n-1)
                            # range=4-0 , n=8 , one element=4/7
                            # 20 values to plot.

array([0.        , 0.21052632, 0.42105263, 0.63157895, 0.84210526,
       1.05263158, 1.26315789, 1.47368421, 1.68421053, 1.89473684,
       2.10526316, 2.31578947, 2.52631579, 2.73684211, 2.94736842,
       3.15789474, 3.36842105, 3.57894737, 3.78947368, 4.        ])

In [43]:
np.linspace(1,3,15)      # 15 values to plot , 2/14 = value of one point.

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ])