In [1]:
import numpy as np

__Generate random numbers using random.rand(x) function __

In [3]:
np.random.rand(5)          # creates random values each time you run this.

array([0.79962664, 0.79972695, 0.79446152, 0.86344839, 0.23455253])

__Create array of random numbers__

In [13]:
x=np.random.rand(4,3,7)        # 4 rows of 3x7 matrix
print(x)
print(np.shape(x))
print(np.ndim(x))

[[[0.31138963 0.5789306  0.61911646 0.58322936 0.37559996 0.58273323
   0.9709497 ]
  [0.36806235 0.72248019 0.25378134 0.58925087 0.94570838 0.08623311
   0.07817231]
  [0.48538011 0.42952962 0.92769154 0.6954335  0.11762222 0.27660742
   0.29666807]]

 [[0.2324274  0.93291345 0.98488476 0.96573305 0.60497911 0.93550424
   0.84767184]
  [0.43928265 0.60382446 0.2877171  0.77514474 0.85731475 0.86937454
   0.47313773]
  [0.42135168 0.8538526  0.64226077 0.97816039 0.06498203 0.54476153
   0.92602144]]

 [[0.22395577 0.10671133 0.70516036 0.49171704 0.24902472 0.19208639
   0.36007057]
  [0.11022205 0.9028522  0.23719259 0.0625775  0.67362553 0.66598578
   0.24275463]
  [0.0810383  0.85596747 0.46940063 0.69172714 0.62955571 0.6763691
   0.3416287 ]]

 [[0.10448698 0.06713778 0.04977815 0.94791047 0.02017539 0.9668657
   0.95891247]
  [0.10043813 0.88510771 0.24607809 0.77779665 0.04954005 0.99272271
   0.98732708]
  [0.95481467 0.32133387 0.15707536 0.59964351 0.77309142 0.83438771
   

In [15]:
np.random.randn(2,3)    # standard normal distribution of random numbers.

array([[-0.72854551, -0.80953736,  2.46269557],
       [ 0.39480719, -0.52593111,  1.15657651]])

In [23]:
### SND of random values , SND of random numbers is the Z-scores

np.random.randn(8)    # SND has mean at 0 and SD=1

array([ 0.71745309, -1.18683982, -1.60790021, -0.09377127, -0.21329417,
        0.184956  ,  0.88162253, -0.77181736])

In [25]:
np.random.rand(8)    

### to reshape the values into some matrix use reshape function, only condition is that the values should be
### equally divisible into the matrix form

__for ex - random.rand(16)   - can be reshaped to 8x2 or 2x8 or 16x1 or 1x16 or 4x4 matrix only and not to 3x6 or anything else

In [31]:
rand_arr= np.random.rand(8) 
print(rand_arr)
print()
rand_arr.reshape(2,4)     ## 2 rows and 4 columns
# rand_arr.reshape(3,3)     ## this wont work as 3x3 is 9 values and we have 16 values, so not allowed

[0.926828   0.00307884 0.70385992 0.02550004 0.65301234 0.10533625
 0.50770928 0.16281041]



ValueError: cannot reshape array of size 8 into shape (3,3)